# clear()
# Tim.load(Rplink)
# setwd(.desktop)
# Tim.load(lassosum)
# 
# library(data.table)
# bfile <- sub("\\.bed$", "", system.file("data/refpanel.bed", package="lassosum"))
# n <- nrow.bfile(bfile)
# beta <- rnorm(ncol.bfile(bfile))
# pval <- runif(ncol.bfile(bfile))
# thres <- seq(0.05, 0.95, by=0.05)
# p1 <- pval.thresh.old(pval, thres, beta, bfile=bfile)
# p2 <- pval.thresh(pval, thres, beta, bfile=bfile)
# summary(as.vector(p1 - p2))
